<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Police Policies</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<script src="site_libs/htmlwidgets-1.5.1/htmlwidgets.js"></script>
<script src="site_libs/plotly-binding-4.9.2.1/plotly.js"></script>
<script src="site_libs/typedarray-0.1/typedarray.min.js"></script>
<link href="site_libs/crosstalk-1.1.0.1/css/crosstalk.css" rel="stylesheet" />
<script src="site_libs/crosstalk-1.1.0.1/js/crosstalk.min.js"></script>
<link href="site_libs/plotly-htmlwidgets-css-1.52.2/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="site_libs/plotly-main-1.52.2/plotly-latest.min.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Black Lives Matter</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Motivation</a>
</li>
<li>
  <a href="BriefOverview.html">A Brief Overview</a>
</li>
<li>
  <a href="dpc.html">Deaths Per Capita</a>
</li>
<li>
  <a href="unarmed.html">Unarmed</a>
</li>
<li>
  <a href="policies.html">Police Policies</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Police Policies</h1>

</div>


<p><strong>Unlike the others, this page is concerned with police killings as a whole, regardless of race.</strong></p>
<p>Each police department works under the state legislature that they are acting in. For cases involving fatal encounters, the relevant laws are any combination of:</p>
<ul>
<li>Requires deescalation</li>
<li>Has use of force continuum (dealing with crime in a step-by-step manner, from a brief warning through to shooting)</li>
<li>Bans chokeholds and strangleholds</li>
<li>Requires warning before shooting</li>
<li>Restricts shooting at moving vehicles</li>
<li>Requires exhausting all other means before shooting</li>
<li>Duty to intervene (challenging the actions of other police officers)</li>
<li>Requires comprehensive reporting</li>
</ul>
<p>To test the effects of state policies, we can compare the predictive power of a linear model <strong>without</strong> the inclusion of policies compared to a linear model <strong>with</strong> the use of policies. <br></p>
<p>Without policies:</p>
<pre><code>## 
## Call:
## lm(formula = Total.Deaths ~ Total + Av.Violent.Crimes + Av.Arrests, 
##     data = police_policies)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -30.529  -6.727  -2.232   4.597  72.689 
## 
## Coefficients:
##                     Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)        9.434e+00  1.642e+00   5.745 1.24e-07 ***
## Total              2.565e-05  6.148e-06   4.172 6.95e-05 ***
## Av.Violent.Crimes  1.686e-03  5.515e-04   3.056  0.00295 ** 
## Av.Arrests        -6.258e-04  1.319e-04  -4.744 7.84e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 13.03 on 90 degrees of freedom
## Multiple R-squared:  0.6321, Adjusted R-squared:  0.6198 
## F-statistic: 51.54 on 3 and 90 DF,  p-value: &lt; 2.2e-16</code></pre>
<p><br></p>
<p>Clearly, the average violent crimes and arrests over the previous five years, along with the total population of the city gives a decent approximation, with 50% of the residuals lying between -6.73 and 4.6. These covariates appear very significant, looking at their p-values. But do the above listed state policies improve the model?</p>
<p><br></p>
<p>With policies:</p>
<pre><code>## 
## Call:
## lm(formula = Total.Deaths ~ Requires.De.Escalation + Has.Use.of.Force.Continuum + 
##     Bans.Chokeholds.and.Strangleholds + Requires.Warning.Before.Shooting + 
##     Restricts.Shooting.at.Moving.Vehicles + Requires.Exhaust.All.Other.Means.Before.Shooting + 
##     Duty.to.Intervene + Requires.Comprehensive.Reporting + Total + 
##     Av.Violent.Crimes + Av.Arrests, data = police_policies)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -28.841  -7.119  -1.715   3.093  66.872 
## 
## Coefficients:
##                                                    Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                                       5.125e+00  4.471e+00   1.146 0.254966    
## Requires.De.Escalation                           -9.219e-01  3.150e+00  -0.293 0.770491    
## Has.Use.of.Force.Continuum                        1.731e+00  3.841e+00   0.451 0.653506    
## Bans.Chokeholds.and.Strangleholds                -1.397e+00  3.506e+00  -0.398 0.691408    
## Requires.Warning.Before.Shooting                  3.878e+00  3.242e+00   1.196 0.235026    
## Restricts.Shooting.at.Moving.Vehicles             1.455e+00  4.001e+00   0.364 0.716983    
## Requires.Exhaust.All.Other.Means.Before.Shooting -2.897e+00  2.930e+00  -0.989 0.325683    
## Duty.to.Intervene                                 2.697e+00  3.037e+00   0.888 0.377141    
## Requires.Comprehensive.Reporting                  2.251e+00  3.107e+00   0.725 0.470804    
## Total                                             2.452e-05  6.498e-06   3.774 0.000303 ***
## Av.Violent.Crimes                                 1.735e-03  5.861e-04   2.960 0.004016 ** 
## Av.Arrests                                       -6.093e-04  1.394e-04  -4.370 3.62e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 13.27 on 82 degrees of freedom
## Multiple R-squared:  0.6525, Adjusted R-squared:  0.6058 
## F-statistic: 13.99 on 11 and 82 DF,  p-value: 1.088e-14</code></pre>
<p><br></p>
<p>None of the policies appear to have an effect, once the previous covariates have been accounted for. Further, this is the case for each policy when tested alone. To put a number on this, we can use an anova test for linear models:</p>
<pre><code>## Analysis of Variance Table
## 
## Model 1: Total.Deaths ~ Total + Av.Violent.Crimes + Av.Arrests
## Model 2: Total.Deaths ~ Requires.De.Escalation + Has.Use.of.Force.Continuum + 
##     Bans.Chokeholds.and.Strangleholds + Requires.Warning.Before.Shooting + 
##     Restricts.Shooting.at.Moving.Vehicles + Requires.Exhaust.All.Other.Means.Before.Shooting + 
##     Duty.to.Intervene + Requires.Comprehensive.Reporting + Total + 
##     Av.Violent.Crimes + Av.Arrests
##   Res.Df   RSS Df Sum of Sq      F Pr(&gt;F)
## 1     90 15275                           
## 2     82 14429  8    846.37 0.6012 0.7742</code></pre>
<p>The meaning of the p-value (0.7742) is the probability of attaining a result as least as extreme as that observed, given the null hypothesis that there is no significant difference between the quality of the models. This result would point towards the models being of very similar predictive power, and the addition of the police policies isn’t significant enough to be included. In context, it appears that once population, violent crime rates and arrest rates are accounted for, police policies seem to have no effect on how many people are killed by the police.</p>
<p>We can also see the R-squared value is 0.6525, meaning that the variance in our model accounts for over 60% of the true variance in the data. This is pretty good for a model of such few variable, especially since human behavior is notoriously hard to model.</p>
<p><br></p>
<p><div id="htmlwidget-822ab55eaa1bd3d75945" style="width:864px;height:768px;" class="plotly html-widget"></div>
<script type="application/json" data-for="htmlwidget-822ab55eaa1bd3d75945">{"x":{"data":[{"x":[19.6869639869691,14.4600016282542,13.4835351048503,14.0980535736258,19.5871797376497,9.89098760592418,16.6788946762147,9.61315539851229,22.085584883166,12.3855896923137,26.4051352979002,13.9165743677777,12.4609262918788,23.3368518696565,13.3555009769271,76.1968163661045,14.334514031393,19.9391740967933,24.3151070684543,11.2199052574194,30.1129691247896,9.80247016598453,36.6162666518531,13.8804993248982,43.5293231245749,13.6319203207967,19.4759409013085,14.1389969772812,22.0866387595228,13.9079866119279,12.1128938607818,11.795743872545,14.8861325835265,9.44052459668181,10.7108266952707,11.9466018907516,68.3737210453876,26.085347375343,13.4116135250977,12.1574391232422,23.9803807861265,14.1374628680855,12.8426104046146,38.1130299802548,9.87938274935412,10.6678655519546,16.6117460754251,105.528336759825,6.81733494974699,13.8170633865293,11.5650145737459,25.1737027687166,9.25371214081269,11.579047674195,23.9136086069693,17.8211213350692,10.5769245281511,14.1266226460003,104.783147838448,16.1868857636718,9.61799245178721,14.6536487922715,23.7244667906421,21.4887604073724,16.9454477429467,13.2965397540985,36.82428530669,38.3108721851383,12.7382214807592,11.99120978243,19.0085975455037,9.72353610899636,14.2613556137598,16.7346150567428,26.2675848582188,14.3338881587425,29.1995253185462,31.7782386727898,30.4252822100129,15.4707642856227,9.73251657935804,23.3056208862073,10.0575960242458,15.2594152207016,14.3286113767105,11.7391857683652,19.5418451519556,4.11241280689615,18.9634093263137,8.49119787712947,17.2636346055455,9.43587582325725,19.7581931717607,8.28634302743565],"y":[32,13,13,14,15,21,32,24,31,10,12,3,5,21,2,76,2,12,10,15,40,7,40,31,13,7,16,9,28,7,23,8,10,3,7,4,70,26,0,7,39,8,8,59,3,3,24,124,22,3,8,24,25,11,16,8,11,12,75,11,11,7,9,48,15,18,33,111,7,2,18,14,8,13,47,10,30,18,22,16,8,23,15,40,13,10,18,9,7,28,27,6,13,3],"text":[" Albuquerque Police Department <br>Population: 545852"," Anaheim Police Department <br>Population: 336265"," Anchorage Police Department <br>Population: 291826"," Arlington Police Department <br>Population: 365438"," Atlanta Police Department <br>Population: 420003"," Aurora Police Department <br>Population: 325078"," Austin Police Department <br>Population: 790390"," Bakersfield Police Department <br>Population: 347483"," Baltimore Police Department <br>Population: 620961"," Baton Rouge Police Department <br>Population: 229493"," Boston Police Department <br>Population: 617594"," Buffalo Police Department <br>Population: 261310"," Chandler Police Department <br>Population: 236123"," Charlotte-Mecklenburg Police Department <br>Population: 731424"," Chesapeake Police Department <br>Population: 222209"," Chicago Police Department <br>Population: 2695598"," Chula Vista Police Department <br>Population: 243916"," Cincinnati Polce Department <br>Population: 296943"," Cleveland Police Department <br>Population: 396815"," Colorado Springs Police Department <br>Population: 416427"," Columbus Division of Police <br>Population: 787033"," Corpus Christi Police Department <br>Population: 305215"," Dallas Police Department <br>Population: 1197816"," Denver Police Department <br>Population: 600158"," Detroit Police Department <br>Population: 713777"," Durham Police Department <br>Population: 228330"," El Paso Police Department <br>Population: 649121"," Fort Wayne Police Department <br>Population: 253691"," Fort Worth Police Department <br>Population: 741206"," Fremont Police Department <br>Population: 214089"," Fresno Police Department <br>Population: 494665"," Garland Police Department <br>Population: 226876"," Glendale Police Department <br>Population: 226721"," Greensboro Police Department <br>Population: 269666"," Henderson Police Department <br>Population: 257729"," Hialeah Police Department <br>Population: 224669"," Houston Police Department <br>Population: 2099451"," Indianapolis Metropolitan Police Department <br>Population: 820445"," Irvine Police Department <br>Population: 212375"," Irving Police Department <br>Population: 216290"," Jacksonville Sheriff's Office <br>Population: 821784"," Jersey City Police Department <br>Population: 247597"," Laredo Police Department <br>Population: 236091"," Las Vegas Metropolitan Police Department <br>Population: 2027868"," Lexington Police Department <br>Population: 295803"," Lincoln Police Department <br>Population: 258379"," Long Beach Police Department <br>Population: 462257"," Los Angeles Police Department <br>Population: 3792621"," Louisville Metro Police Department <br>Population: 597337"," Lubbock Police Department <br>Population: 229573"," Madison Police Department <br>Population: 233209"," Memphis Police Department <br>Population: 646889"," Mesa Police Department <br>Population: 439041"," Miami Police Department <br>Population: 399457"," Milwaukee Police Department <br>Population: 594833"," Minneapolis Police Department <br>Population: 382578"," Metropolitan Nashville Police Department <br>Population: 601222"," New Orleans Police Department <br>Population: 343829"," New York Police Department <br>Population: 8175133"," Newark Police Department <br>Population: 277140"," Norfolk Police Department <br>Population: 242803"," North Las Vegas Police Department <br>Population: 216961"," Oakland Police Department <br>Population: 390724"," Oklahoma City Police Department <br>Population: 579999"," Omaha Police Department <br>Population: 408958"," Orlando Police Department <br>Population: 238300"," Philadelphia Police Department <br>Population: 1526006"," Phoenix Police Department <br>Population: 1445632"," Pittsburgh Police Department <br>Population: 305704"," Plano Police Department <br>Population: 259841"," Portland Police Bureau <br>Population: 583776"," Reno Police Department <br>Population: 225221"," Riverside Police Department <br>Population: 303871"," Sacramento Police Department <br>Population: 466488"," San Antonio Police Department <br>Population: 1327407"," San Bernardino Police Department <br>Population: 209924"," San Diego Police Department <br>Population: 1307402"," San Francisco Police Department <br>Population: 805235"," San Jose Police Department <br>Population: 945942"," Santa Ana Police Department <br>Population: 324528"," Scottsdale Police Department <br>Population: 217385"," Seattle Police Department <br>Population: 608660"," Spokane Police Department <br>Population: 208916"," St. Louis Metropolitan Police Department <br>Population: 319294"," St. Paul Police Department <br>Population: 285068"," St. Petersburg Police Department <br>Population: 244769"," Stockton Police Department <br>Population: 291707"," Tampa Police Department <br>Population: 335709"," Toledo Police Department <br>Population: 287208"," Tucson Police Department <br>Population: 520116"," Tulsa Police Department <br>Population: 391906"," Virginia Beach Police Department <br>Population: 437994"," Wichita Police Department <br>Population: 382368"," Winston-Salem Police Department <br>Population: 229617"],"type":"scatter","mode":"markers","marker":{"autocolorscale":false,"color":"rgba(248,118,109,1)","opacity":0.5,"size":[9.62774800603103,6.06459859009345,4.96635907472394,6.68238680454766,7.69926881182865,5.80908592954552,12.5292756616726,6.30977760312609,10.6068952215947,2.66381176825197,10.5650169121463,4.02548541777714,3.00639682406639,11.8966903204561,2.21520976962957,25.5065668569979,3.35916182535042,5.10583185391279,7.28544881784562,7.63698914059546,12.4941485216415,5.32298696395793,16.2244981859406,10.3453357620244,11.7005047373075,2.59827456212182,10.9506524604229,3.74986457697457,12.0040128974933,1.52407159390899,8.89621039131991,2.51351177260148,2.50427655746511,4.30559165617276,3.89862958071326,2.37799904962303,22.288376286252,12.8393557226588,1.31515580444861,1.74634302835884,12.8529909670773,3.51201240670241,3.00485062351747,21.869566712431,5.07511771915774,3.9219929465478,8.3986320567507,30.5444258639282,10.3093364875362,2.66825098010909,2.86165189445951,10.9238146748783,8.02229834045323,7.33384157383057,10.2772728330653,7.01860611532416,10.3588799302289,6.23104422908959,45.3543307086614,4.54019162855183,3.31137764786031,1.80724631231854,7.17256858068442,10.0851519396683,7.50515373457824,3.10953241004872,18.6659495866973,18.0991639499493,5.33552634511078,3.97398792472721,10.1344283393329,2.41273909459529,5.28835795203792,8.46533065172798,17.2308533268443,0.883880711698951,17.0794603264691,12.6834094156606,14.0583848886962,5.79621309904095,1.84442712907604,10.453053292479,0.377952755905512,5.67214456626959,4.77538410853684,3.39527130181367,4.96306504253703,6.05217119105659,4.83674364781575,9.26747059418554,7.19461993339956,8.00488877146588,7.01458981053369,2.67068888291524],"symbol":"circle","line":{"width":1.88976377952756,"color":"rgba(248,118,109,1)"}},"hoveron":"points","name":"red","legendgroup":"red","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[-0.958383390750299,110.599132957472],"y":[-0.958383390750299,110.599132957472],"text":"","type":"scatter","mode":"lines","line":{"width":1.88976377952756,"color":"rgba(0,0,0,1)","dash":"solid"},"hoveron":"points","showlegend":false,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null}],"layout":{"margin":{"t":41.7534246575342,"r":7.30593607305936,"b":38.1735159817352,"l":43.1050228310502},"plot_bgcolor":"rgba(235,235,235,1)","paper_bgcolor":"rgba(255,255,255,1)","font":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187},"title":{"text":"Without Policies","font":{"color":"rgba(0,0,0,1)","family":"","size":17.5342465753425},"x":0,"xref":"paper"},"xaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[-0.958383390750299,110.599132957472],"tickmode":"array","ticktext":["0","25","50","75","100"],"tickvals":[1.11022302462516e-16,25,50,75,100],"categoryorder":"array","categoryarray":["0","25","50","75","100"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.65296803652968,"tickwidth":0.66417600664176,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.689497716895},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(255,255,255,1)","gridwidth":0.66417600664176,"zeroline":false,"anchor":"y","title":{"text":"Model Prediction","font":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187}},"scaleanchor":"y","scaleratio":1,"hoverformat":".2f"},"yaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[-6.2,130.2],"tickmode":"array","ticktext":["0","40","80","120"],"tickvals":[0,40,80,120],"categoryorder":"array","categoryarray":["0","40","80","120"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.65296803652968,"tickwidth":0.66417600664176,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.689497716895},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(255,255,255,1)","gridwidth":0.66417600664176,"zeroline":false,"anchor":"x","title":{"text":"True Death Count","font":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187}},"scaleanchor":"x","scaleratio":1,"hoverformat":".2f"},"shapes":[{"type":"rect","fillcolor":null,"line":{"color":null,"width":0,"linetype":[]},"yref":"paper","xref":"paper","x0":0,"x1":1,"y0":0,"y1":1}],"showlegend":false,"legend":{"bgcolor":"rgba(255,255,255,1)","bordercolor":"transparent","borderwidth":1.88976377952756,"font":{"color":"rgba(0,0,0,1)","family":"","size":11.689497716895}},"hovermode":"closest","barmode":"relative"},"config":{"doubleClick":"reset","showSendToCloud":false},"source":"A","attrs":{"4214722b1b5a":{"x":{},"y":{},"size":{},"colour":{},"text":{},"type":"scatter"},"42146c10ec44":{"intercept":{},"slope":{}}},"cur_data":"4214722b1b5a","visdat":{"4214722b1b5a":["function (y) ","x"],"42146c10ec44":["function (y) ","x"]},"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.2,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script> <br></p>
<p>The black line represents a perfect model where the model predicts the exact count every time. Since this model only contains 3 parameters, it’s hard to point fingers at certain departments since there may be data out there that provides more information to better predict the data. However it gives a rudimentary idea of the police departments who don’t fit the general trend, based on population size, average arrests and average violent crimes. Police departments above the black line kill citizens more than the model predicts, and departments below the line kill citizens less than the model predicts. NYPD, in this plot and the one in the Deaths Per Capita tab, have shown that they have a low deaths per capita for all races, and also kill far less frequently than the model predicts. Phoenix PD and St. Louis Metropolitan PD seem to be the exact opposite. In the last few years, St. Louis Metropolitan PD have been involved in a number of <a href="https://en.wikipedia.org/wiki/Metropolitan_Police_Department,_City_of_St._Louis#Controversies">controversies</a> which reinforces what the data shows.</p>
<p>There’s clearly big problems within certain departments. This model can’t be used alone to make concrete accusations, but it can be used to show how predictable the number of deaths is; three simple guesses were enough to explain most of the variability in the data. Since this model isn’t bad, we can at least ask questions about those departments who have large residuals: are there any key differences in how NYPD and Phoenix PD handle crime? What factors might be consistent in those with high residuals? These questions may lead to answers that improve on this model but, for now, we may only speculate on guilty departments.</p>
<p>At the very least, police policies appear insignificant in attempting to predict the number of killings a department is responsible for. This raises more questions: are the policies being implemented thoroughly enough? Are policies being ignored? Could new policies be introduced with more serious consequences?</p>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
